export enum PAID_BY_VALUES {
  VISHAL = "Vishal",
  SONALI = "Sonali",
}

export const PAID_BY_OPTIONS = [
  {
    value: PAID_BY_VALUES.VISHAL,
    label: PAID_BY_VALUES.VISHAL,
  },
  {
    value: PAID_BY_VALUES.SONALI,
    label: PAID_BY_VALUES.SONALI,
  },
];

export enum PAID_FOR_VALUES {
  VISHAL = "Vishal",
  SONALI = "Sonali",
  BOTH = "Both",
}

export const PAID_FOR_OPTIONS = [
  {
    value: PAID_FOR_VALUES.VISHAL,
    label: PAID_FOR_VALUES.VISHAL,
  },
  {
    value: PAID_FOR_VALUES.BOTH,
    label: PAID_FOR_VALUES.BOTH,
  },
  {
    value: PAID_FOR_VALUES.SONALI,
    label: PAID_FOR_VALUES.SONALI,
  },
];

export enum EXPENSE_CATEGORY_VALUES {
  FOOD = "Food",
  SOCIAL = "Social",
  TRANSPORTATION = "Transportation",
  HOUSEHOLD = "Household",
  APPAREL = "Apparel",
  BEAUTY = "Beauty",
  HEALTH = "Health",
  EDUCATION = "Education",
  GIFT = "Gift",
  HOME = "Home",
  SHOPPING = "Shopping",
  BIRTHDAY = "Birthday",
  VACATION = "Vacation",
}

export const EXPENSE_CATEGORY_OPTIONS = [
  EXPENSE_CATEGORY_VALUES.FOOD,
  EXPENSE_CATEGORY_VALUES.SOCIAL,
  EXPENSE_CATEGORY_VALUES.TRANSPORTATION,
  EXPENSE_CATEGORY_VALUES.HOUSEHOLD,
  EXPENSE_CATEGORY_VALUES.APPAREL,
  EXPENSE_CATEGORY_VALUES.BEAUTY,
  EXPENSE_CATEGORY_VALUES.HEALTH,
  EXPENSE_CATEGORY_VALUES.EDUCATION,
  EXPENSE_CATEGORY_VALUES.GIFT,
  EXPENSE_CATEGORY_VALUES.HOME,
  EXPENSE_CATEGORY_VALUES.SHOPPING,
  EXPENSE_CATEGORY_VALUES.BIRTHDAY,
  EXPENSE_CATEGORY_VALUES.VACATION,
];
